export const WEATHER = {
  UPDATE_CURRENT_WEATHER: "UPDATE_CURRENT_WEATHER",
  UPDATE_WEATHER: "UPDATE_WEATHER",
  CHANGE_LOCATION: "CHANGE_LOCATION",
  CHANGE_PERIOD: "CHANGE_PERIOD",
  SELECTED_DAY: "SELECTED_DAY",
};
